import React, { Component } from 'react';
import SuccessChild from './SuccessChild';
import SuccessStory from './SuccessStory';
import UserSignIn from './UserSignIn';

export default class Success extends Component {
	constructor(props) {
		super(props);

		this.state = {
			value: 0,
		};
	}

	// function to change the state; it will be passed down to SuccessStory comp,
	// and the state changes made by the component will be reflected in this component.
	changeState = (newValue) => {
		this.setState({
			value: newValue,
		});
	};

	render() {
		return (
			<div>
				<hr />
				<h2 className='comp'>Success Comp.</h2>
				<p className='quote'>{this.props.message}
				</p>
				<p>
					The random value generated by the SuccessStory component is:{' '}
					<strong>{this.state.value}</strong>
				</p>

				<SuccessChild
					name='Jay'
					address='Somewhere on earth'
					// Pass down the SuccessStory component as well as
					// the state update function as props
					stateChangeFunction={this.changeState}
					Component={SuccessStory}
				/>

				<UserSignIn />

			</div>
		);
	}
}
